version: "3.1"

services:
  foodspot-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: foodspot-server
    ports:
      - 8080:8080
    environment:
      - CLOUDANT_ID=''
      - CLOUDANT_API_KEY=''
      - TOKEN_SECRET=''
