# This workflow is for building a docker image for pull requests so that it
# can be easily tested by other developers
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets
# 3. Update environment variables
#

name: Build and publish branch image

# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-south
  DOCKER_USER: foodspotgroup
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: foodspot-server
  CLOUDANT_API_KEY: ${{ secrets.CLOUDANT_API_KEY }}
  CLOUDANT_ID: ${{ secrets.CLOUDANT_ID }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  DISCORD_BOT: Builder
  DISCORD_PIPELINE_WEBHOOK: ${{ secrets.DISCORD_PIPELINE_WEBHOOK }}

jobs:

  # Builds the docker image
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Log intoo docker so that we can push to registry
      - name: Docker login
        run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USER} --password-stdin

      # Retrieve the branch name
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      # Retrieve the image tags
      - name: Get docker image tags
        id: get-tags
        run: |
          branch_name="${{ steps.branch-name.outputs.current_branch }}"
          escaped_branch=$(echo $branch_name | sed -e 's/[^0-9A-Za-z-]/-/g')
          last_sha=${GITHUB_SHA: -5}
          image_tag="${escaped_branch}"-"${last_sha}"
          branch_image="${DOCKER_USER}"/"${IMAGE_NAME}":"${image_tag}"
          echo "::set-output name=branch_image::${branch_image}"

      # Build both the branch and latest images
      - name: Build image with Docker
        id: build-image
        run: |
          branch_image="${{steps.get-tags.outputs.branch_image}}"
          docker build -t "${branch_image}" \
            -f Dockerfile.prod \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the images to docker hub
      - name: Push images to docker
        run: |
          branch_image="${{steps.get-tags.outputs.branch_image}}"
          docker push "${branch_image}"

      # Send success message to our discord server
      - name: Send success message to Discord
        if: ${{ success() }}
        run: |
          branch_image="${{steps.get-tags.outputs.branch_image}}"
          message="Successfully built and deployed the following to Dockerhub:\n- \`${branch_image}\`\n"
          curl -H "Content-Type: application/json" \
            -d "{\"username\": \"${DISCORD_BOT}\", \"content\": \"${message}\"}" \
            ${DISCORD_PIPELINE_WEBHOOK}

      # Send error message to our discord server
      - name: Send error message to Discord
        if: ${{ failure() }}
        run: |
          branch_image="${{steps.get-tags.outputs.branch_image}}"
          latest_image="${{steps.get-tags.outputs.latest_image}}"
          message="Error deploying the following to Dockerhub:\n- \`${branch_image}\`\n"
          curl -H "Content-Type: application/json" \
            -d "{\"username\": \"${DISCORD_BOT}\", \"content\": \"${message}\"}" \
            ${DISCORD_PIPELINE_WEBHOOK}
